stages:
  - docker-build
  - deploy

docker-build:
  stage: docker-build
  image: docker:latest
  services:
    - name: docker:dind
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build -t "$CI_REGISTRY_USER/$CI_REGISTRY_IMAGE" .
    - docker push "$CI_REGISTRY_USER/$CI_REGISTRY_IMAGE"
    - echo "Registry image:" "$CI_REGISTRY_USER/$CI_REGISTRY_IMAGE"
  only:
    refs:
      - master

deploy:
  stage: deploy
  image: kroniak/ssh-client
  before_script:
    - echo "deploying app"
    - apk add openssh-client
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
  script:
    - ssh -o StrictHostKeyChecking=no root@$PROD_SERVER_IP "docker pull $CI_REGISTRY_USER/$CI_REGISTRY_IMAGE"
    - ssh -o StrictHostKeyChecking=no root@$PROD_SERVER_IP "docker stop $CI_REGISTRY_IMAGE || true && docker rm $CI_REGISTRY_IMAGE || true"
    - ssh -o StrictHostKeyChecking=no root@$PROD_SERVER_IP "docker run -d --rm -p 3000:3000 --name $CI_REGISTRY_IMAGE $CI_REGISTRY_USER/$CI_REGISTRY_IMAGE"
  only:
    refs:
      - master